version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: chmod +x manage.py
          name: Permission
      - run:       
          command: ./manage.py test
          name: Test
      - run:
          name: Run Linting
          command: |
              pylint scriptfortests.py || python pylint_exit.py $?
             
workflows:
  main:
    jobs:
      - build-and-test
