version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Run Linting
          command: pylint main_script.py
      - run:
          name: Testing
          command: pytest main_script_test.py 
      - run:       
          name: Launch
          command: python main_script.py
             
workflows:
  main:
    jobs:
      - build-and-test
